ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from .views import store, cart, checkout, updateItem

app_name = 'store'
urlpatterns = [
    path('',store, name='store'),
    path('cart/',cart, name='cart'),
    path('checkout/',checkout, name='checkout'),
    path('update_item/',updateItem, name= 'update_item'),

]

store/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Customer(models.Model):
    user = models.OneToOneField(User, blank=True, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200)

    def __str__(self):
        return self.name



class Product(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True)
    price = models.FloatField()
    digital = models.BooleanField(default=False, null=True, blank=False)
    image = models.ImageField(null=True, blank=True)

    def __str__(self):
        return self.name
    
    @property
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url



class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True)
    date_created = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    transaction = models.CharField(max_length=200, null=True)

    def __str__(self):
        return str(self.id)

    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total



class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL,null= True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL,null=True)
    quantity = models.IntegerField(default=0,null=True,blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total
    


class ShippingAddress(models.Model):
    customer = models.ForeignKey(Customer,on_delete=models.SET_NULL,null= True, blank=True)
    order = models.ForeignKey(Order,on_delete=models.SET_NULL,null=True,blank=True)
    address = models.CharField(max_length=200,null=False)
    city = models.CharField(max_length=200, null=False)
    state = models.CharField(max_length=200, null=False)
    zipcode = models.CharField(max_length=200, null=False)
    date_added= models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.customer

store/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from .models import Product, Order, OrderItem, ShippingAddress, Customer
import json
# Create your views here.


def store(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer = customer, complete = False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items
    else:
        items = []
        order = {'get_cart_total':0, 'get_cart_items':0}
        cartItems = order['get_cart_items']

    products = Product.objects.all()
    context = {'products':products, 'cartItems':cartItems}
    return render(request, 'store/Store.html', context)


def cart(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete = False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items


    else:
        items = []
        order = {'get_cart_total':0, 'get_cart_items':0}
        cartItems = order['get_cart_items']


    context = {'items': items, 'order':order, 'cartItems': cartItems}
    return render(request, 'store/Cart.html', context)


def checkout(request):
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete = False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items

    else:
        items = []
        order = {'get_cart_total':0, 'get_cart_items':0}
        cartItems = order['get_cart_items']


    context = {'items': items, 'order':order, 'cartItems': cartItems}
    return render(request, 'store/Checkout.html', context)


def updateItem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']

    print('Action:',action)
    print('productId:',productId)

    customer = request.user.customer
    product = Product.objects.get(id = productId)
    order, created = Order.objects.get_or_create(customer = customer, complete = False)

    orderItem, created = OrderItem.objects.get_or_create(order = order, product = product)

    if action == 'add':
        orderItem.quantity = (orderItem.quantity + 1)
    elif action == 'remove':
        orderItem.quantity = (orderItem.quantity - 1)

    orderItem.save()

    if orderItem.quantity <= 0:
        orderItem.delete()

    return JsonResponse('Item is was added', safe = False)

store/templates/store/Cart.html
{% extends 'store/Main.html' %}
{% load static %}
{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="box-element">
                <a class="btn btn-outline-dark" href="{% url 'store:store' %}"> &#x2190; Continue Shopping</a>
                <br>
                <br>
                <table class="table">
                    <tr>
                        <th><h5>Items: <strong>{{order.get_cart_items}}</strong></h5></th>
                        <th><h5>Total: <strong>${{order.get_cart_total|floatformat:2}}</strong></h5></th>
                        <th><a style="float: right; margin: 5px" class="btn btn-success" href="{% url 'store:checkout' %}">Checkout</a></th>


                    </tr>
                </table>
               
            </div> 
            <br>
            
            <div class="box-element">
                
                <div class="cart-row">
                    <div style="flex:2"></div>
                    <div style="flex:2"><strong>Items</strong></div>
                    <div style="flex:1"><strong>Price</strong></div>
                    <div style="flex:1"><strong>Quantity </strong></div>
                    <div style="flex:1"><strong>Total </strong></div>
                </div>
                {% for item in items%}
                <div class="cart-row">
                    <div style="flex:2"><img src="{{item.product.imageURL}}" class="row-image" alt=""></div>
                    <div style="flex:2">{{item.product.name}}</div>
                    <div style="flex:1">${{item.product.price| floatformat:2}}</div>
                    <div style="flex:1">
                        <p class="quantity">{{item.quantity}}</p>
                        <div class="quantity">
                            <img data-product="{{item.product.id}}" data-action="add" class="chg-quantity update-cart" src="{% static 'images/arrow-up.png' %}" alt="">
                            <img data-product="{{item.product.id}}" data-action="remove" class="chg-quantity update-cart" src="{% static 'images/arrow-down.png' %}" alt="">
                        </div>

                    </div>
                    <div style="flex:1">{{item.get_total}}</div>
                </div>
                {% endfor %}
            </div>
        </div>            
    </div>
    
    

{% endblock content %}

store/templates/store/Checkout.html
{% extends 'store/Main.html' %}
{% load static %}
{% block content %}
    <div class="row">
        <div class="col-lg-6">
            <div class="box-element" id="form-wrapper">              
                <form action="" id="form">
                    <div id="user-infor">
                        <div class="form-field">
                            <input required class="form-control" type="text" name="name" placeholder="Name...">
                        </div>
                        <div class="form-field">
                            <input required class="form-control" type="email" name="email" placeholder="Email...">
                        </div>
                    </div>
                    <div id="shipping-infor">
                        <hr>
                        <p>Shipping information</p>
                        <hr>
                        <div class="form-field">
                            <input required class="form-control" type="text" name="address" placeholder="Address...">
                        </div>
                        <div class="form-field">
                            <input required class="form-control" type="text" name="city" placeholder="City...">
                        </div>
                        <div class="form-field">
                            <input required class="form-control" type="text" name="state" placeholder="State...">
                        </div>
                        <div class="form-field">
                            <input required class="form-control" type="text" name="zip code" placeholder="Zip Code...">
                        </div>

                    </div>
                </form>
                <hr>
                <input type="submit" id="form-buttom" class="btn btn-success btn-block" value="Continue" >
            </div>
            <br>

            <div class="box-element hidden" id="payment-info">
                <small>Paypal Options</small>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="box-element">
                <a class="btn btn-outline-dark" href="{% url 'store:cart' %}">&#x2190; Back to Cart</a>
                <br>
                <hr>
                <h1>Order Summary</h1>
                <hr>
                {% for item in items %}
                <div class="cart-row">
                    <div style="flex:2"><img src="{{item.product.imageURL}}" alt="" class="row-image"></div>
                    <div style="flex:2">{{item.product.name}}</div>
                    <div style="flex:1">${{item.product.price}}</div>
                    <div style="flex:1">{{item.quantity}}</div>
                </div>
                {% endfor %}
                <h5>Items: {{order.get_cart_items}}</h5>
                <h5>Total: ${{order.get_cart_total | floatformat:2}}</h5>
            </div>
        </div>
    </div>

{% endblock content %}

store/templates/store/Main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>my_store.com</title>
    <script type="text/javascript">
      var user = '{{request.user}}' ;

      function getToken(name) {
      var cookieValue = null;
      if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {

          var cookie = cookies[i].trim();
          // Does this cookie string begin with the name we want?
          if (cookie.substring(0, name.length + 1) === (name + '=')) {
            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
            break;
          }
        }
      }
      return cookieValue;
    }
    var csrftoken = getToken('csrftoken');
    </script>

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'store:store' %}">Ecom</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'store:store' %}">Store <span class="sr-only">(current)</span></a>
            </li>
            
          </ul>
          <div class="form-inline my-2 my-lg-0"  >
            <a href="#"class="btn btn-warning" id="abc" >Login</a>
            
            <a href="{% url 'store:cart' %}" > 
               <img  id="cart-icon" src="{% static 'images/cart.png' %}">
           </a>
           <p id="cart-total">{{cartItems}}</p>
   
       </div>
        </div>
      </nav>

    <div class="container">
        {% block content %}
        {% endblock %}

    </div>
    

    {% block footer %}
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'js/cart1.js' %}"></script>
</body>
</html>

store/templates/store/Store.html
{% extends 'store/Main.html' %}
{% load static %}
{% block content %}
    <div class="row">
        {% for product in products %}
        <div class="col-lg-4">
            <img class="thumbnail" src="{{product.imageURL}}" alt="">
            <div class="box-element product">
                <h6><strong>{{product.name}}</strong></h6>
                <hr>
                <button data-product={{product.id}} data-action="add" class="btn btn-outline-secondary add-btn update-cart">Add to cart</button>
                <a class="btn btn-outline-success" href="#">View</a>
                <h4 style="float:right;"><strong>${{product.price|floatformat:2}} </strong></h4>
            </div>
        </div>
        {% endfor %}
    </div>


{% endblock content %}